package com.idan.pokemon_hub.model

import com.idan.pokemon_hub.repository.PokemonRepository
import org.springframework.boot.CommandLineRunner
import org.springframework.stereotype.Component
import java.net.URI
import java.net.URL

@Component
class DataInitializer(
    private val pokemonRepository: PokemonRepository
) : CommandLineRunner {

    override fun run(vararg args: String?) {
        val baseUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/"

        val pokemons = listOf(
            Pokemon(1, "Bulbasaur", "Grass/Poison", URI("${baseUrl}1.png").toURL()),
            Pokemon(2, "Ivysaur", "Grass/Poison", URI("${baseUrl}2.png").toURL()),
            Pokemon(3, "Venusaur", "Grass/Poison", URI("${baseUrl}3.png").toURL()),
            Pokemon(4, "Charmander", "Fire", URI("${baseUrl}4.png").toURL()),
            Pokemon(5, "Charmeleon", "Fire", URI("${baseUrl}5.png").toURL()),
            Pokemon(6, "Charizard", "Fire/Flying", URI("${baseUrl}6.png").toURL()),
            Pokemon(7, "Squirtle", "Water", URI("${baseUrl}7.png").toURL()),
            Pokemon(8, "Wartortle", "Water", URI("${baseUrl}8.png").toURL()),
            Pokemon(9, "Blastoise", "Water", URI("${baseUrl}9.png").toURL()),
            Pokemon(10, "Caterpie", "Bug", URI("${baseUrl}10.png").toURL()),
            Pokemon(11, "Metapod", "Bug", URI("${baseUrl}11.png").toURL()),
            Pokemon(12, "Butterfree", "Bug/Flying", URI("${baseUrl}12.png").toURL()),
            Pokemon(13, "Weedle", "Bug/Poison", URI("${baseUrl}13.png").toURL()),
            Pokemon(14, "Kakuna", "Bug/Poison", URI("${baseUrl}14.png").toURL()),
            Pokemon(15, "Beedrill", "Bug/Poison", URI("${baseUrl}15.png").toURL()),
            Pokemon(16, "Pidgey", "Normal/Flying", URI("${baseUrl}16.png").toURL()),
            Pokemon(17, "Pidgeotto", "Normal/Flying", URI("${baseUrl}17.png").toURL()),
            Pokemon(18, "Pidgeot", "Normal/Flying", URI("${baseUrl}18.png").toURL()),
            Pokemon(19, "Rattata", "Normal", URI("${baseUrl}19.png").toURL()),
            Pokemon(20, "Raticate", "Normal", URI("${baseUrl}20.png").toURL()),
            Pokemon(21, "Spearow", "Normal/Flying", URI("${baseUrl}21.png").toURL()),
            Pokemon(22, "Fearow", "Normal/Flying", URI("${baseUrl}22.png").toURL()),
            Pokemon(23, "Ekans", "Poison", URI("${baseUrl}23.png").toURL()),
            Pokemon(24, "Arbok", "Poison", URI("${baseUrl}24.png").toURL()),
            Pokemon(25, "Pikachu", "Electric", URI("${baseUrl}25.png").toURL()),
            Pokemon(26, "Raichu", "Electric", URI("${baseUrl}26.png").toURL()),
            Pokemon(27, "Sandshrew", "Ground", URI("${baseUrl}27.png").toURL()),
            Pokemon(28, "Sandslash", "Ground", URI("${baseUrl}28.png").toURL()),
            Pokemon(29, "Nidoran♀", "Poison", URI("${baseUrl}29.png").toURL()),
            Pokemon(30, "Nidorina", "Poison", URI("${baseUrl}30.png").toURL()),
            Pokemon(31, "Nidoqueen", "Poison/Ground", URI("${baseUrl}31.png").toURL()),
            Pokemon(32, "Nidoran♂", "Poison", URI("${baseUrl}32.png").toURL()),
            Pokemon(33, "Nidorino", "Poison", URI("${baseUrl}33.png").toURL()),
            Pokemon(34, "Nidoking", "Poison/Ground", URI("${baseUrl}34.png").toURL()),
            Pokemon(35, "Clefairy", "Fairy", URI("${baseUrl}35.png").toURL()),
            Pokemon(36, "Clefable", "Fairy", URI("${baseUrl}36.png").toURL()),
            Pokemon(37, "Vulpix", "Fire", URI("${baseUrl}37.png").toURL()),
            Pokemon(38, "Ninetales", "Fire", URI("${baseUrl}38.png").toURL()),
            Pokemon(39, "Jigglypuff", "Normal/Fairy", URI("${baseUrl}39.png").toURL()),
            Pokemon(40, "Wigglytuff", "Normal/Fairy", URI("${baseUrl}40.png").toURL()),
            Pokemon(41, "Zubat", "Poison/Flying", URI("${baseUrl}41.png").toURL()),
            Pokemon(42, "Golbat", "Poison/Flying", URI("${baseUrl}42.png").toURL()),
            Pokemon(43, "Oddish", "Grass/Poison", URI("${baseUrl}43.png").toURL()),
            Pokemon(44, "Gloom", "Grass/Poison", URI("${baseUrl}44.png").toURL()),
            Pokemon(45, "Vileplume", "Grass/Poison", URI("${baseUrl}45.png").toURL()),
            Pokemon(46, "Paras", "Bug/Grass", URI("${baseUrl}46.png").toURL()),
            Pokemon(47, "Parasect", "Bug/Grass", URI("${baseUrl}47.png").toURL()),
            Pokemon(48, "Venonat", "Bug/Poison", URI("${baseUrl}48.png").toURL()),
            Pokemon(49, "Venomoth", "Bug/Poison", URI("${baseUrl}49.png").toURL()),
            Pokemon(50, "Diglett", "Ground", URI("${baseUrl}50.png").toURL()),
            Pokemon(51, "Dugtrio", "Ground", URI("${baseUrl}51.png").toURL()),
            Pokemon(52, "Meowth", "Normal", URI("${baseUrl}52.png").toURL()),
            Pokemon(53, "Persian", "Normal", URI("${baseUrl}53.png").toURL()),
            Pokemon(54, "Psyduck", "Water", URI("${baseUrl}54.png").toURL()),
            Pokemon(55, "Golduck", "Water", URI("${baseUrl}55.png").toURL()),
            Pokemon(56, "Mankey", "Fighting", URI("${baseUrl}56.png").toURL()),
            Pokemon(57, "Primeape", "Fighting", URI("${baseUrl}57.png").toURL()),
            Pokemon(58, "Growlithe", "Fire", URI("${baseUrl}58.png").toURL()),
            Pokemon(59, "Arcanine", "Fire", URI("${baseUrl}59.png").toURL()),
            Pokemon(60, "Poliwag", "Water", URI("${baseUrl}60.png").toURL()),
            Pokemon(61, "Poliwhirl", "Water", URI("${baseUrl}61.png").toURL()),
            Pokemon(62, "Politoed", "Water", URI("${baseUrl}62.png").toURL()),
            Pokemon(63, "Abra", "Psychic", URI("${baseUrl}63.png").toURL()),
            Pokemon(64, "Kadabra", "Psychic", URI("${baseUrl}64.png").toURL()),
            Pokemon(65, "Alakazam", "Psychic", URI("${baseUrl}65.png").toURL()),
            Pokemon(66, "Machop", "Fighting", URI("${baseUrl}66.png").toURL()),
            Pokemon(67, "Machoke", "Fighting", URI("${baseUrl}67.png").toURL()),
            Pokemon(68, "Machamp", "Fighting", URI("${baseUrl}68.png").toURL()),
            Pokemon(69, "Bellsprout", "Grass/Poison", URI("${baseUrl}69.png").toURL()),
            Pokemon(70, "Weepinbell", "Grass/Poison", URI("${baseUrl}70.png").toURL()),
            Pokemon(71, "Victreebel", "Grass/Poison", URI("${baseUrl}71.png").toURL()),
            Pokemon(72, "Tentacool", "Water/Poison", URI("${baseUrl}72.png").toURL()),
            Pokemon(73, "Tentacruel", "Water/Poison", URI("${baseUrl}73.png").toURL()),
            Pokemon(74, "Geodude", "Rock/Ground", URI("${baseUrl}74.png").toURL()),
            Pokemon(75, "Graveler", "Rock/Ground", URI("${baseUrl}75.png").toURL()),
            Pokemon(76, "Golem", "Rock/Ground", URI("${baseUrl}76.png").toURL()),
            Pokemon(77, "Ponyta", "Fire", URI("${baseUrl}77.png").toURL()),
            Pokemon(78, "Rapidash", "Fire", URI("${baseUrl}78.png").toURL()),
            Pokemon(79, "Slowpoke", "Water/Psychic", URI("${baseUrl}79.png").toURL()),
            Pokemon(80, "Slowbro", "Water/Psychic", URI("${baseUrl}80.png").toURL()),
            Pokemon(81, "Magnemite", "Electric/Steel", URI("${baseUrl}81.png").toURL()),
            Pokemon(82, "Magneton", "Electric/Steel", URI("${baseUrl}82.png").toURL()),
            Pokemon(83, "Farfetch'd", "Normal/Flying", URI("${baseUrl}83.png").toURL()),
            Pokemon(84, "Doduo", "Normal/Flying", URI("${baseUrl}84.png").toURL()),
            Pokemon(85, "Dodrio", "Normal/Flying", URI("${baseUrl}85.png").toURL()),
            Pokemon(86, "Seel", "Water", URI("${baseUrl}86.png").toURL()),
            Pokemon(87, "Dewgong", "Water/Ice", URI("${baseUrl}87.png").toURL()),
            Pokemon(88, "Grimer", "Poison", URI("${baseUrl}88.png").toURL()),
            Pokemon(89, "Muk", "Poison", URI("${baseUrl}89.png").toURL()),
            Pokemon(90, "Shellder", "Water", URI("${baseUrl}90.png").toURL()),
            Pokemon(91, "Cloyster", "Water/Ice", URI("${baseUrl}91.png").toURL()),
            Pokemon(92, "Gastly", "Ghost/Poison", URI("${baseUrl}92.png").toURL()),
            Pokemon(93, "Haunter", "Ghost/Poison", URI("${baseUrl}93.png").toURL()),
            Pokemon(94, "Gengar", "Ghost/Poison", URI("${baseUrl}94.png").toURL()),
            Pokemon(95, "Onix", "Rock/Ground", URI("${baseUrl}95.png").toURL()),
            Pokemon(96, "Drowzee", "Psychic", URI("${baseUrl}96.png").toURL()),
            Pokemon(97, "Hypno", "Psychic", URI("${baseUrl}97.png").toURL()),
            Pokemon(98, "Krabby", "Water", URI("${baseUrl}98.png").toURL()),
            Pokemon(99, "Kingler", "Water", URI("${baseUrl}99.png").toURL()),
            Pokemon(100, "Exeggcute", "Grass/Psychic", URI("${baseUrl}100.png").toURL()),
            Pokemon(101, "Exeggutor", "Grass/Psychic", URI("${baseUrl}101.png").toURL()),
            Pokemon(102, "Cubone", "Ground", URI("${baseUrl}102.png").toURL()),
            Pokemon(103, "Marowak", "Ground", URI("${baseUrl}103.png").toURL()),
            Pokemon(104, "Hitmonlee", "Fighting", URI("${baseUrl}104.png").toURL()),
            Pokemon(105, "Hitmonchan", "Fighting", URI("${baseUrl}105.png").toURL()),
            Pokemon(106, "Lickitung", "Normal", URI("${baseUrl}106.png").toURL()),
            Pokemon(107, "Koffing", "Poison", URI("${baseUrl}107.png").toURL()),
            Pokemon(108, "Weezing", "Poison", URI("${baseUrl}108.png").toURL()),
            Pokemon(109, "Rhyhorn", "Rock/Ground", URI("${baseUrl}109.png").toURL()),
            Pokemon(110, "Rhydon", "Rock/Ground", URI("${baseUrl}110.png").toURL()),
            Pokemon(111, "Chansey", "Normal", URI("${baseUrl}111.png").toURL()),
            Pokemon(112, "Tangela", "Grass", URI("${baseUrl}112.png").toURL()),
            Pokemon(113, "Kangaskhan", "Normal", URI("${baseUrl}113.png").toURL()),
            Pokemon(114, "Horsea", "Water", URI("${baseUrl}114.png").toURL()),
            Pokemon(115, "Seadra", "Water", URI("${baseUrl}115.png").toURL()),
            Pokemon(116, "Goldeen", "Water", URI("${baseUrl}116.png").toURL()),
            Pokemon(117, "Seaking", "Water", URI("${baseUrl}117.png").toURL()),
            Pokemon(118, "Staryu", "Water", URI("${baseUrl}118.png").toURL()),
            Pokemon(119, "Starmie", "Water/Psychic", URI("${baseUrl}119.png").toURL()),
            Pokemon(120, "Mr. Mime", "Psychic/Fairy", URI("${baseUrl}120.png").toURL()),
            Pokemon(121, "Scyther", "Bug/Flying", URI("${baseUrl}121.png").toURL()),
            Pokemon(122, "Jynx", "Ice/Psychic", URI("${baseUrl}122.png").toURL()),
            Pokemon(123, "Electabuzz", "Electric", URI("${baseUrl}123.png").toURL()),
            Pokemon(124, "Magmar", "Fire", URI("${baseUrl}124.png").toURL()),
            Pokemon(125, "Pinsir", "Bug", URI("${baseUrl}125.png").toURL()),
            Pokemon(126, "Tauros", "Normal", URI("${baseUrl}126.png").toURL()),
            Pokemon(127, "Magikarp", "Water", URI("${baseUrl}127.png").toURL()),
            Pokemon(128, "Gyarados", "Water/Flying", URI("${baseUrl}128.png").toURL()),
            Pokemon(129, "Lapras", "Water/Ice", URI("${baseUrl}129.png").toURL()),
            Pokemon(130, "Ditto", "Normal", URI("${baseUrl}130.png").toURL()),
            Pokemon(131, "Eevee", "Normal", URI("${baseUrl}131.png").toURL()),
            Pokemon(132, "Vaporeon", "Water", URI("${baseUrl}132.png").toURL()),
            Pokemon(133, "Jolteon", "Electric", URI("${baseUrl}133.png").toURL()),
            Pokemon(134, "Flareon", "Fire", URI("${baseUrl}134.png").toURL()),
            Pokemon(135, "Porygon", "Normal", URI("${baseUrl}.png").toURL()),
            Pokemon(136, "Omanyte", "Rock/Water", URI("${baseUrl}136.png").toURL()),
            Pokemon(137, "Omastar", "Rock/Water", URI("${baseUrl}137.png").toURL()),
            Pokemon(138, "Kabuto", "Rock/Water", URI("${baseUrl}138.png").toURL()),
            Pokemon(139, "Kabutops", "Rock/Water", URI("${baseUrl}139.png").toURL()),
            Pokemon(140, "Aerodactyl", "Rock/Flying", URI("${baseUrl}140.png").toURL()),
            Pokemon(141, "Snorlax", "Normal", URI("${baseUrl}141.png").toURL()),
            Pokemon(142, "Articuno", "Ice/Flying", URI("${baseUrl}142.png").toURL()),
            Pokemon(143, "Zapdos", "Electric/Flying", URI("${baseUrl}143.png").toURL()),
            Pokemon(144, "Moltres", "Fire/Flying", URI("${baseUrl}144.png").toURL()),
            Pokemon(145, "Dratini", "Dragon", URI("${baseUrl}145.png").toURL()),
            Pokemon(146, "Dragonair", "Dragon", URI("${baseUrl}146.png").toURL()),
            Pokemon(147, "Dragonite", "Dragon/Flying", URI("${baseUrl}147.png").toURL()),
            Pokemon(148, "Mewtwo", "Psychic", URI("${baseUrl}148.png").toURL()),
            Pokemon(149, "Mew", "Psychic", URI("${baseUrl}149.png").toURL()),
            Pokemon(150, "Mewtwo", "Psychic", URI("${baseUrl}150.png").toURL()), // Mewtwo appears twice for different sprites
            Pokemon(151, "Mew", "Psychic", URI("${baseUrl}151.png").toURL())
        )

        pokemonRepository.saveAll(pokemons)  // Save to the H2 database
    }
}