package com.idan.pokemon_hub.model

import com.idan.pokemon_hub.repository.PokemonRepository
import org.springframework.boot.CommandLineRunner
import org.springframework.stereotype.Component
import java.net.URL

@Component
class DataInitializer(
    private val pokemonRepository: PokemonRepository
) : CommandLineRunner {

    override fun run(vararg args: String?) {
        val baseUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/"

        val pokemons = listOf(
            Pokemon(1, "Bulbasaur", "Grass/Poison", URL("$baseUrl}1.png")),
            Pokemon(2, "Ivysaur", "Grass/Poison", URL("$baseUrl}2.png")),
            Pokemon(3, "Venusaur", "Grass/Poison", URL("$baseUrl}3.png")),
            Pokemon(4, "Charmander", "Fire", URL("$baseUrl}4.png")),
            Pokemon(5, "Charmeleon", "Fire", URL("$baseUrl}5.png")),
            Pokemon(6, "Charizard", "Fire/Flying", URL("$baseUrl}6.png")),
            Pokemon(7, "Squirtle", "Water", URL("$baseUrl}7.png")),
            Pokemon(8, "Wartortle", "Water", URL("$baseUrl}8.png")),
            Pokemon(9, "Blastoise", "Water", URL("$baseUrl}9.png")),
            Pokemon(10, "Caterpie", "Bug", URL("$baseUrl}10.png")),
            Pokemon(11, "Metapod", "Bug", URL("$baseUrl}11.png")),
            Pokemon(12, "Butterfree", "Bug/Flying", URL("$baseUrl}12.png")),
            Pokemon(13, "Weedle", "Bug/Poison", URL("$baseUrl}13.png")),
            Pokemon(14, "Kakuna", "Bug/Poison", URL("$baseUrl}14.png")),
            Pokemon(15, "Beedrill", "Bug/Poison", URL("$baseUrl}15.png")),
            Pokemon(16, "Pidgey", "Normal/Flying", URL("$baseUrl}16.png")),
            Pokemon(17, "Pidgeotto", "Normal/Flying", URL("$baseUrl}17.png")),
            Pokemon(18, "Pidgeot", "Normal/Flying", URL("$baseUrl}18.png")),
            Pokemon(19, "Rattata", "Normal", URL("$baseUrl}19.png")),
            Pokemon(20, "Raticate", "Normal", URL("$baseUrl}20.png")),
            Pokemon(21, "Spearow", "Normal/Flying", URL("$baseUrl}21.png")),
            Pokemon(22, "Fearow", "Normal/Flying", URL("$baseUrl}22.png")),
            Pokemon(23, "Ekans", "Poison", URL("$baseUrl}23.png")),
            Pokemon(24, "Arbok", "Poison", URL("$baseUrl}24.png")),
            Pokemon(25, "Pikachu", "Electric", URL("$baseUrl}25.png")),
            Pokemon(26, "Raichu", "Electric", URL("$baseUrl}26.png")),
            Pokemon(27, "Sandshrew", "Ground", URL("$baseUrl}27.png")),
            Pokemon(28, "Sandslash", "Ground", URL("$baseUrl}28.png")),
            Pokemon(29, "Nidoran♀", "Poison", URL("$baseUrl}29.png")),
            Pokemon(30, "Nidorina", "Poison", URL("$baseUrl}30.png")),
            Pokemon(31, "Nidoqueen", "Poison/Ground", URL("$baseUrl}31.png")),
            Pokemon(32, "Nidoran♂", "Poison", URL("$baseUrl}32.png")),
            Pokemon(33, "Nidorino", "Poison", URL("$baseUrl}33.png")),
            Pokemon(34, "Nidoking", "Poison/Ground", URL("$baseUrl}34.png")),
            Pokemon(35, "Clefairy", "Fairy", URL("$baseUrl}35.png")),
            Pokemon(36, "Clefable", "Fairy", URL("$baseUrl}36.png")),
            Pokemon(37, "Vulpix", "Fire", URL("$baseUrl}37.png")),
            Pokemon(38, "Ninetales", "Fire", URL("$baseUrl}38.png")),
            Pokemon(39, "Jigglypuff", "Normal/Fairy", URL("$baseUrl}39.png")),
            Pokemon(40, "Wigglytuff", "Normal/Fairy", URL("$baseUrl}40.png")),
            Pokemon(41, "Zubat", "Poison/Flying", URL("$baseUrl}41.png")),
            Pokemon(42, "Golbat", "Poison/Flying", URL("$baseUrl}42.png")),
            Pokemon(43, "Oddish", "Grass/Poison", URL("$baseUrl}43.png")),
            Pokemon(44, "Gloom", "Grass/Poison", URL("$baseUrl}44.png")),
            Pokemon(45, "Vileplume", "Grass/Poison", URL("$baseUrl}45.png")),
            Pokemon(46, "Paras", "Bug/Grass", URL("$baseUrl}46.png")),
            Pokemon(47, "Parasect", "Bug/Grass", URL("$baseUrl}47.png")),
            Pokemon(48, "Venonat", "Bug/Poison", URL("$baseUrl}48.png")),
            Pokemon(49, "Venomoth", "Bug/Poison", URL("$baseUrl}49.png")),
            Pokemon(50, "Diglett", "Ground", URL("$baseUrl}50.png")),
            Pokemon(51, "Dugtrio", "Ground", URL("$baseUrl}51.png")),
            Pokemon(52, "Meowth", "Normal", URL("$baseUrl}52.png")),
            Pokemon(53, "Persian", "Normal", URL("$baseUrl}53.png")),
            Pokemon(54, "Psyduck", "Water", URL("$baseUrl}54.png")),
            Pokemon(55, "Golduck", "Water", URL("$baseUrl}55.png")),
            Pokemon(56, "Mankey", "Fighting", URL("$baseUrl}56.png")),
            Pokemon(57, "Primeape", "Fighting", URL("$baseUrl}57.png")),
            Pokemon(58, "Growlithe", "Fire", URL("$baseUrl}58.png")),
            Pokemon(59, "Arcanine", "Fire", URL("$baseUrl}59.png")),
            Pokemon(60, "Poliwag", "Water", URL("$baseUrl}60.png")),
            Pokemon(61, "Poliwhirl", "Water", URL("$baseUrl}61.png")),
            Pokemon(62, "Politoed", "Water", URL("$baseUrl}62.png")),
            Pokemon(63, "Abra", "Psychic", URL("$baseUrl}63.png")),
            Pokemon(64, "Kadabra", "Psychic", URL("$baseUrl}64.png")),
            Pokemon(65, "Alakazam", "Psychic", URL("$baseUrl}65.png")),
            Pokemon(66, "Machop", "Fighting", URL("$baseUrl}66.png")),
            Pokemon(67, "Machoke", "Fighting", URL("$baseUrl}67.png")),
            Pokemon(68, "Machamp", "Fighting", URL("$baseUrl}68.png")),
            Pokemon(69, "Bellsprout", "Grass/Poison", URL("$baseUrl}69.png")),
            Pokemon(70, "Weepinbell", "Grass/Poison", URL("$baseUrl}70.png")),
            Pokemon(71, "Victreebel", "Grass/Poison", URL("$baseUrl}71.png")),
            Pokemon(72, "Tentacool", "Water/Poison", URL("$baseUrl}72.png")),
            Pokemon(73, "Tentacruel", "Water/Poison", URL("$baseUrl}73.png")),
            Pokemon(74, "Geodude", "Rock/Ground", URL("$baseUrl}74.png")),
            Pokemon(75, "Graveler", "Rock/Ground", URL("$baseUrl}75.png")),
            Pokemon(76, "Golem", "Rock/Ground", URL("$baseUrl}76.png")),
            Pokemon(77, "Ponyta", "Fire", URL("$baseUrl}77.png")),
            Pokemon(78, "Rapidash", "Fire", URL("$baseUrl}78.png")),
            Pokemon(79, "Slowpoke", "Water/Psychic", URL("$baseUrl}79.png")),
            Pokemon(80, "Slowbro", "Water/Psychic", URL("$baseUrl}80.png")),
            Pokemon(81, "Magnemite", "Electric/Steel", URL("$baseUrl}81.png")),
            Pokemon(82, "Magneton", "Electric/Steel", URL("$baseUrl}82.png")),
            Pokemon(83, "Farfetch'd", "Normal/Flying", URL("$baseUrl}83.png")),
            Pokemon(84, "Doduo", "Normal/Flying", URL("$baseUrl}84.png")),
            Pokemon(85, "Dodrio", "Normal/Flying", URL("$baseUrl}85.png")),
            Pokemon(86, "Seel", "Water", URL("$baseUrl}86.png")),
            Pokemon(87, "Dewgong", "Water/Ice", URL("$baseUrl}87.png")),
            Pokemon(88, "Grimer", "Poison", URL("$baseUrl}88.png")),
            Pokemon(89, "Muk", "Poison", URL("$baseUrl}89.png")),
            Pokemon(90, "Shellder", "Water", URL("$baseUrl}90.png")),
            Pokemon(91, "Cloyster", "Water/Ice", URL("$baseUrl}91.png")),
            Pokemon(92, "Gastly", "Ghost/Poison", URL("$baseUrl}92.png")),
            Pokemon(93, "Haunter", "Ghost/Poison", URL("$baseUrl}93.png")),
            Pokemon(94, "Gengar", "Ghost/Poison", URL("$baseUrl}94.png")),
            Pokemon(95, "Onix", "Rock/Ground", URL("$baseUrl}95.png")),
            Pokemon(96, "Drowzee", "Psychic", URL("$baseUrl}96.png")),
            Pokemon(97, "Hypno", "Psychic", URL("$baseUrl}97.png")),
            Pokemon(98, "Krabby", "Water", URL("$baseUrl}98.png")),
            Pokemon(99, "Kingler", "Water", URL("$baseUrl}99.png")),
            Pokemon(100, "Exeggcute", "Grass/Psychic", URL("$baseUrl}100.png")),
            Pokemon(101, "Exeggutor", "Grass/Psychic", URL("$baseUrl}101.png")),
            Pokemon(102, "Cubone", "Ground", URL("$baseUrl}102.png")),
            Pokemon(103, "Marowak", "Ground", URL("$baseUrl}103.png")),
            Pokemon(104, "Hitmonlee", "Fighting", URL("$baseUrl}104.png")),
            Pokemon(105, "Hitmonchan", "Fighting", URL("$baseUrl}105.png")),
            Pokemon(106, "Lickitung", "Normal", URL("$baseUrl}106.png")),
            Pokemon(107, "Koffing", "Poison", URL("$baseUrl}107.png")),
            Pokemon(108, "Weezing", "Poison", URL("$baseUrl}108.png")),
            Pokemon(109, "Rhyhorn", "Rock/Ground", URL("$baseUrl}109.png")),
            Pokemon(110, "Rhydon", "Rock/Ground", URL("$baseUrl}110.png")),
            Pokemon(111, "Chansey", "Normal", URL("$baseUrl}111.png")),
            Pokemon(112, "Tangela", "Grass", URL("$baseUrl}112.png")),
            Pokemon(113, "Kangaskhan", "Normal", URL("$baseUrl}113.png")),
            Pokemon(114, "Horsea", "Water", URL("$baseUrl}114.png")),
            Pokemon(115, "Seadra", "Water", URL("$baseUrl}115.png")),
            Pokemon(116, "Goldeen", "Water", URL("$baseUrl}116.png")),
            Pokemon(117, "Seaking", "Water", URL("$baseUrl}117.png")),
            Pokemon(118, "Staryu", "Water", URL("$baseUrl}118.png")),
            Pokemon(119, "Starmie", "Water/Psychic", URL("$baseUrl}119.png")),
            Pokemon(120, "Mr. Mime", "Psychic/Fairy", URL("$baseUrl}120.png")),
            Pokemon(121, "Scyther", "Bug/Flying", URL("$baseUrl}121.png")),
            Pokemon(122, "Jynx", "Ice/Psychic", URL("$baseUrl}122.png")),
            Pokemon(123, "Electabuzz", "Electric", URL("$baseUrl}123.png")),
            Pokemon(124, "Magmar", "Fire", URL("$baseUrl}124.png")),
            Pokemon(125, "Pinsir", "Bug", URL("$baseUrl}125.png")),
            Pokemon(126, "Tauros", "Normal", URL("$baseUrl}126.png")),
            Pokemon(127, "Magikarp", "Water", URL("$baseUrl}127.png")),
            Pokemon(128, "Gyarados", "Water/Flying", URL("$baseUrl}128.png")),
            Pokemon(129, "Lapras", "Water/Ice", URL("$baseUrl}129.png")),
            Pokemon(130, "Ditto", "Normal", URL("$baseUrl}130.png")),
            Pokemon(131, "Eevee", "Normal", URL("$baseUrl}131.png")),
            Pokemon(132, "Vaporeon", "Water", URL("$baseUrl}132.png")),
            Pokemon(133, "Jolteon", "Electric", URL("$baseUrl}133.png")),
            Pokemon(134, "Flareon", "Fire", URL("$baseUrl}134.png")),
            Pokemon(135, "Porygon", "Normal", URL("$baseUrl}.png")),
            Pokemon(136, "Omanyte", "Rock/Water", URL("$baseUrl}136.png")),
            Pokemon(137, "Omastar", "Rock/Water", URL("$baseUrl}137.png")),
            Pokemon(138, "Kabuto", "Rock/Water", URL("$baseUrl}138.png")),
            Pokemon(139, "Kabutops", "Rock/Water", URL("$baseUrl}139.png")),
            Pokemon(140, "Aerodactyl", "Rock/Flying", URL("$baseUrl}140.png")),
            Pokemon(141, "Snorlax", "Normal", URL("$baseUrl}141.png"))
        )

        pokemonRepository.saveAll(pokemons)  // Save to the H2 database
    }
}